import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import StaticSection from "@/components/StaticSection";
import SmartJobSections from "@/components/SmartJobSections";
import JobFeatureHighlight from "@/components/JobFeatureHighlight";
import PricingSection from "@/components/PricingSection";
import CTASection from "@/components/CTASection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HireLoop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
    >
      <body className="">
      <NavBar></NavBar>
     <StaticSection></StaticSection>
     <SmartJobSections></SmartJobSections>
     <JobFeatureHighlight></JobFeatureHighlight>
     <PricingSection></PricingSection>
    <CTASection></CTASection>
      <main>{children}</main>
      <Footer></Footer></body>
    </html>
  );
}
